/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package real.app

import com.beust.klaxon.JsonObject
import com.beust.klaxon.JsonReader
import com.beust.klaxon.Klaxon
import org.junit.Assert
import java.io.StringReader


fun main(args: Array<String>) {

    // this creates a json object
    val Drivers = """
      {
        "driver": "Sebastian Vettle",
        "team": "Ferrari",
        "chapionships": "4"
      }
    """

    // this uses the json reader to read the json string
    JsonReader(StringReader(Drivers)).use { reader ->
        reader.beginObject() {
            var driver: String? = null
            var team: String? = null
            var champioship: Int? = null
            while (reader.hasNext()) {
                val readName = reader.nextName()
                when (readName) {
                    "name" -> driver = reader.nextString()
                    "team" -> team = reader.nextString()
                    "championship" -> champioship = reader.nextInt()
                    else -> Assert.fail("Unexpected driver: $readName")
                }
            }
        }
    }
}